server:
  port: 8080

Spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQl
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true